In [18]:
"""
VARIABLE DESCRIPTIONS:
survival        Survival
                (0 = No; 1 = Yes)
pclass          Passenger Class
                (1 = 1st; 2 = 2nd; 3 = 3rd)
name            Name
sex             Sex
age             Age
sibsp           Number of Siblings/Spouses Aboard
parch           Number of Parents/Children Aboard
ticket          Ticket Number
fare            Passenger Fare
cabin           Cabin
embarked        Port of Embarkation
                (C = Cherbourg; Q = Queenstown; S = Southampton)

SPECIAL NOTES:
Pclass is a proxy for socio-economic status (SES)
 1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower

Age is in Years; Fractional if Age less than One (1)
 If the Age is Estimated, it is in the form xx.5
"""

import csv as csv
import numpy as np

csv_file_object = csv.reader(open('./data/train.csv','rb'))

#read in header and data
header = csv_file_object.next()
data = []
for row in csv_file_object:
    data.append(row)
    
data = np.array(data)

for i in range(len(header)):
    print str(i) + "   " + header[i]

0   PassengerId
1   Survived
2   Pclass
3   Name
4   Sex
5   Age
6   SibSp
7   Parch
8   Ticket
9   Fare
10   Cabin
11   Embarked


In [22]:
fare_ceiling = 40

#run through data, if fare >= 40, replace with fare 39 (ceiling)
data[ data[0::,9].astype(np.float) >= fare_ceiling, 9] = fare_ceiling - 1.0

#create fare brackets of size 10
fare_bracket_size = 10
number_of_price_brackets = fare_ceiling / fare_bracket_size

#create number of classes (given in data: 1st, 2nd, 3rd)
number_of_classes = len(np.unique(data[0::,2]))

In [23]:
#create 2x3x4 array matrix of bins (female/male, 1st/2nd/3rd class, price brackets)
survival_table = np.zeros([2,number_of_classes,number_of_price_brackets],float)
print(survival_table)



[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
